//
//  ListFiltersModels.swift
//  CameraFilterApp
//
//  Created by siheo on 11/30/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListFilters
{
    // MARK: Use cases
    
    struct FilterInfo {
        let filterId: UUID
        let filterName: String
        let filterAppliedImage: UIImage
    }
    
    enum FetchFilters {
        struct Request {
        }
        struct Response {
            var filters: [CameraFilter]
        }
        struct ViewModel {
            var filterInfo: [FilterInfo]
        }
    }
}
