//
//  CameraPreviewPresenter.swift
//  CameraFilterApp
//
//  Created by siheo on 11/27/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CameraPreviewPresentationLogic
{
    func presentAllFilters(response: CameraPreview.FetchFilters.Response)
    func presentFrameImage(response: CameraPreview.DrawFrameImage.Response)
}

class CameraPreviewPresenter: CameraPreviewPresentationLogic
{
    weak var viewController: CameraPreviewDisplayLogic?
    
    // MARK: Do something
    
    func presentAllFilters(response: CameraPreview.FetchFilters.Response) {
        let filters = response.filters
        
        var filterNames:[String] = filters.map { $0.displayName }
        filterNames.insert("원본", at: 0)
        
        let viewModel = CameraPreview.FetchFilters.ViewModel(filterNames: filterNames)
        viewController?.displayFilterNames(viewModel: viewModel)
    }
    
    func presentFrameImage(response: CameraPreview.DrawFrameImage.Response) {
        let frameImage = response.frameImage
        let commandBuffer = response.commandBuffer
        
        let viewModel = CameraPreview.DrawFrameImage.ViewModel(frameImage: frameImage, commandBuffer: commandBuffer)
        viewController?.displayFrameImage(viewModel: viewModel)
    }
}
