//
//  CameraPreviewModels.swift
//  CameraFilterApp
//
//  Created by siheo on 11/27/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MetalKit

enum CameraPreview
{
    // MARK: Use cases
    
    enum StartSession {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum FetchFilters {
        struct Request {
        }
        struct Response {
            var filters: [CameraFilter]
        }
        struct ViewModel {
            var filterNames: [String]
        }
    }
    
    enum ApplyFilter {
        struct Request {
            var filterName: String
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum DrawPreviewBuffer {
        struct Request {
            var metalView: MTKView
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
