//
//  CameraPreviewWorker.swift
//  CameraFilterApp
//
//  Created by siheo on 11/27/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AVFoundation
import RxSwift

class CameraPreviewWorker
{
    enum CameraError: LocalizedError {
        case noCamera(String)
        
        var errorDescription: String? {
            switch self {
            case .noCamera(let string):
                return string
            }
        }
    }
    
    var cameraDevice: Single<AVCaptureDevice> = {
        return Observable<AVCaptureDevice>.create { observer in
            let discoverySession = AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInWideAngleCamera,.builtInUltraWideCamera], mediaType: .video, position: .back)

            if let cameraDevice = discoverySession.devices.first {
                observer.onNext(cameraDevice)
                observer.onCompleted()
            } else {
                observer.onError(CameraError.noCamera("사용할 수 있는 카메라가 존재하지 않습니다"))
            }
            
            return Disposables.create()
        }.asSingle()
    }()
}
